Repository prgrms-be-devcourse/NBE1_1_Team7, pull requests merged in 2024-09, with the labels that each got.

#4 Feat/#2
  backend/.gitignore
  backend/src/main/java/grepp/coffee/backend/BackendApplication.java
  backend/src/main/java/grepp/coffee/backend/common/exception/member/MemberException.java
  backend/src/main/java/grepp/coffee/backend/controller/order/OrderController.java
  backend/src/main/java/grepp/coffee/backend/controller/order/request/OrderRegisterRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/order/request/OrderUpdateRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/orderitem/request/OrderItemRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/product/ProductController.java
  backend/src/main/java/grepp/coffee/backend/controller/product/request/ProductRegisterRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/product/request/ProductUpdateRequest.java
  backend/src/main/java/grepp/coffee/backend/model/entity/order/Order.java
  backend/src/main/java/grepp/coffee/backend/model/entity/product/Product.java
  backend/src/main/java/grepp/coffee/backend/model/repository/member/MemberRepository.java
  backend/src/main/java/grepp/coffee/backend/model/repository/order/OrderRepository.java
  backend/src/main/java/grepp/coffee/backend/model/repository/orderitem/OrderItemRepository.java
  backend/src/main/java/grepp/coffee/backend/model/repository/product/ProductRepository.java
  backend/src/main/java/grepp/coffee/backend/model/service/member/MemberService.java
  backend/src/main/java/grepp/coffee/backend/model/service/order/OrderService.java
  backend/src/main/java/grepp/coffee/backend/model/service/product/ProductService.java
Labels: ✨Feature, 🔨Refactor

#10 Refactor: Member예외처리 수정
  backend/src/main/java/grepp/coffee/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/grepp/coffee/backend/model/service/member/MemberService.java
Labels: 🔨Refactor

#14 Feature: 리뷰 api 구현
  backend/src/main/java/grepp/coffee/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/grepp/coffee/backend/common/exception/review/ReviewException.java
  backend/src/main/java/grepp/coffee/backend/controller/review/ReviewController.java
  backend/src/main/java/grepp/coffee/backend/controller/review/request/ReviewRegisterRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/review/request/ReviewUpdateRequest.java
  backend/src/main/java/grepp/coffee/backend/model/entity/review/Review.java
  backend/src/main/java/grepp/coffee/backend/model/repository/review/ReviewRepository.java
  backend/src/main/java/grepp/coffee/backend/model/service/review/ReviewService.java
  backend/src/test/java/grepp/coffee/backend/MockTestConfig.java
  backend/src/test/java/grepp/coffee/backend/controller/ReviewControllerTest.java
  backend/src/test/java/grepp/coffee/backend/model/entity/member/MemberFixture.java
  backend/src/test/java/grepp/coffee/backend/model/entity/product/ProductFixture.java
  backend/src/test/java/grepp/coffee/backend/model/entity/review/ReviewFixture.java
Labels: ✨Feature

#13 Feature: FAQ 등록, 조회, 수정, 삭제 구현
  backend/.gitignore
  backend/src/main/java/grepp/coffee/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/grepp/coffee/backend/common/exception/question/QuestionException.java
  backend/src/main/java/grepp/coffee/backend/controller/question/QuestionController.java
  backend/src/main/java/grepp/coffee/backend/controller/question/request/QuestionRegisterRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/question/request/QuestionUpdateRequest.java
  backend/src/main/java/grepp/coffee/backend/model/entity/question/Question.java
  backend/src/main/java/grepp/coffee/backend/model/repository/question/QuestionRepository.java
  backend/src/main/java/grepp/coffee/backend/model/service/question/QuestionService.java
Labels: ✨Feature

#15 Feature: 상품 할인, 인기 상품 조회 API 구현
  .gitignore
  backend/src/main/java/grepp/coffee/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/grepp/coffee/backend/controller/product/ProductController.java
  backend/src/main/java/grepp/coffee/backend/model/entity/product/Product.java
  backend/src/main/java/grepp/coffee/backend/model/repository/product/ProductRepository.java
  backend/src/main/java/grepp/coffee/backend/model/service/order/OrderService.java
  backend/src/main/java/grepp/coffee/backend/model/service/product/ProductService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/database.yml
Labels: ✨Feature

#16 Feature: 장바구니 CRUD API 구현
  .idea/.gitignore
  backend/src/main/java/grepp/coffee/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/grepp/coffee/backend/common/exception/member/CartException.java
  backend/src/main/java/grepp/coffee/backend/controller/member/CartController.java
  backend/src/main/java/grepp/coffee/backend/controller/member/request/CartRegisterRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/member/request/CartUpdateRequest.java
  backend/src/main/java/grepp/coffee/backend/model/repository/member/CartRepository.java
  backend/src/main/java/grepp/coffee/backend/model/service/member/CartService.java
  backend/src/main/java/grepp/coffee/backend/model/service/order/OrderService.java
Labels: ✨Feature

#19 Feature: 리뷰 삭제 api 구현
  backend/src/main/java/grepp/coffee/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/grepp/coffee/backend/controller/review/ReviewController.java
  backend/src/main/java/grepp/coffee/backend/controller/review/request/ReviewDeleteRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/review/request/ReviewRegisterRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/review/request/ReviewUpdateRequest.java
  backend/src/main/java/grepp/coffee/backend/model/service/review/ReviewService.java
  backend/src/test/java/grepp/coffee/backend/controller/ReviewControllerTest.java
  backend/src/test/java/grepp/coffee/backend/model/entity/review/ReviewFixture.java
Labels: ✨Feature

#24 Feature/#12
  .gitignore
  backend/.DS_Store
  backend/src/.DS_Store
  backend/src/main/java/grepp/coffee/backend/controller/product/ProductController.java
  backend/src/main/java/grepp/coffee/backend/controller/product/request/ProductDetailResponse.java
  backend/src/main/java/grepp/coffee/backend/model/repository/product/ProductRepository.java
  backend/src/main/java/grepp/coffee/backend/model/repository/review/ReviewRepository.java
  backend/src/main/java/grepp/coffee/backend/model/service/product/ProductService.java
  docs/Branch strategy and pull-quest.md
Labels: ✨Feature

#20 Feature: 회원 관련 기능 구현
  .idea/.gitignore
  backend/src/main/java/grepp/coffee/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/grepp/coffee/backend/controller/member/MemberController.java
  backend/src/main/java/grepp/coffee/backend/controller/member/request/MemberLoginRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/member/request/MemberRegisterRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/member/request/MemberUpdateRequest.java
  backend/src/main/java/grepp/coffee/backend/model/repository/member/MemberRepository.java
  backend/src/main/java/grepp/coffee/backend/model/service/member/MemberService.java
  backend/src/main/resources/database.yml
Labels: ✨Feature

#26 Feature: 장바구니 기능 주문 API에 추가
  .idea/workspace.xml
  backend/.DS_Store
  backend/src/.DS_Store
  backend/src/main/java/grepp/coffee/backend/controller/order/OrderController.java
  backend/src/main/java/grepp/coffee/backend/model/repository/member/CartRepository.java
  backend/src/main/java/grepp/coffee/backend/model/service/member/CartService.java
  backend/src/main/java/grepp/coffee/backend/model/service/order/OrderService.java
  backend/src/main/resources/database.yml
Labels: ✨Feature, 🔨Refactor

#31 Feature: 상품 할인, 상품 CUD에 관리자 권한 확인
  backend/src/main/java/grepp/coffee/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/grepp/coffee/backend/controller/product/ProductController.java
  backend/src/main/java/grepp/coffee/backend/model/service/product/ProductService.java
  backend/src/test/java/grepp/coffee/backend/model/entity/member/MemberFixture.java
  backend/src/test/java/grepp/coffee/backend/service/ProductServiceTest.java
Labels: ✨Feature

#33 Docs: README.md 수정 및 Swagger 추가
  README.md
  backend/build.gradle
  backend/src/main/java/grepp/coffee/backend/controller/question/QuestionController.java
Labels: 📃 Docs

#35 Feature: FAQ API에 member 추가
  backend/src/main/java/grepp/coffee/backend/common/exception/ExceptionMessage.java
  backend/src/main/java/grepp/coffee/backend/controller/question/QuestionController.java
  backend/src/main/java/grepp/coffee/backend/controller/question/request/QuestionDeleteRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/question/request/QuestionRegisterRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/question/request/QuestionUpdateRequest.java
  backend/src/main/java/grepp/coffee/backend/model/repository/question/QuestionRepository.java
  backend/src/main/java/grepp/coffee/backend/model/service/question/QuestionService.java
Labels: ✨Feature

#34 Update: password String으로 변경 및 passwordEncoder 적용 완료
  backend/build.gradle
  backend/src/main/java/grepp/coffee/backend/config/SecurityConfig.java
  backend/src/main/java/grepp/coffee/backend/controller/member/MemberController.java
  backend/src/main/java/grepp/coffee/backend/controller/member/request/MemberLoginRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/member/request/MemberRegisterRequest.java
  backend/src/main/java/grepp/coffee/backend/controller/member/request/MemberUpdateRequest.java
  backend/src/main/java/grepp/coffee/backend/model/entity/member/Member.java
  backend/src/main/java/grepp/coffee/backend/model/entity/member/constant/ROLE.java
  backend/src/main/java/grepp/coffee/backend/model/service/member/MemberService.java
Labels: ✨Feature

#40 Docs: Swagger description 추가
  backend/src/main/java/grepp/coffee/backend/controller/member/CartController.java
  backend/src/main/java/grepp/coffee/backend/controller/member/MemberController.java
  backend/src/main/java/grepp/coffee/backend/controller/order/OrderController.java
  backend/src/main/java/grepp/coffee/backend/controller/product/ProductController.java
  backend/src/main/java/grepp/coffee/backend/controller/product/ProductSearchController.java
  backend/src/main/java/grepp/coffee/backend/controller/question/QuestionController.java
  backend/src/main/java/grepp/coffee/backend/controller/review/ReviewController.java
Labels: 📃 Docs
